### ISSUE TITLE
Bug du parametre wholeword avec des accents

### ISSUE THREAD

**Issue by jonquet** [sifrproject/ncbo_annotator#1]
Essayer le mot préexisatnt
Même avec le bon parametrage avec whole word, le mot pré (dans Mesh) matche.
A regarder de plus près.

**Comment by jonquet** [comment]
Bug reproduit sur "pharmacocinétique": l'accent provoque une annotation avec "tique" même si " Match Partial Words" n'est pas sélectionné.

Il semblerait que MGREP considère les caractères spéciaux comme un caratère de fin de mot. 

D’après @twktheainur cela pourrait venir du fait qu'il faut donner du ISO Latin1 a l'Annotator tandis que MGREP lui prend du UTF8 visiblement.

**Comment by amineabdaoui** [comment]
Le dictionnaire du Mgrep est effectivement encodé en utf-8. J'ai essayé de l'encoder en ISO Latin1 (avec la commande iconv) mais cela n'a pas réglé le problème.
Le soucis pourrait venir du serveur qui fait tourner Mgrep, car en se connectant en telnet comme expliqué sur le lien ci-dessous je n'arrive pas à taper les accents (si "é" à l'écran j'obtiens le caractère "C)").
https://www.bioontology.org/wiki/index.php/Annotator_Documentation
Je met en pièce jointe une capture d'écran de deux tests que j'effectue en appelant Mgrep avec les mots "tiller" et "prétiller" (sachant que le concept "tiller" est présent dans le dictionnaire).
![capture](https://cloud.githubusercontent.com/assets/17952908/20561513/3db1cda2-b17f-11e6-8ae2-0dbc75ba95c0.jpg)

**Comment by jonquet** [comment]
Amine est-ce qu'on ton fichier qui contient le texte a annoter est aussi en UTF-8 ?
Il faut etre sur que le bug se produit en envoyant de l'UTF-8 en input et en appellant MGREP (i) en ligne de commande; (ii) via le daemon.

Suivant les elements de reponses, si le bug est confirmé niveau MGREP, je peux demander aux gens de UMICH.

**Comment by amineabdaoui** [comment]
Après plusieurs tests (i) ligne de commande et (ii) via le daemon, nous avons confirmé que le problème venait de MGREP. Dés qu'il y a un accent MGREP considère la suite comme un nouveau mot tout en prenant en considération le mot complet.

Pour plus de détails je met ci-dessous le résumé des tests que nous avons effectué avec tout encodé en UTF-8 pour texte: "pharmacocinétique".

**(i) Ligne de commande**
Seule l'option Match Longest Only est disponible (-l)

i.1. Quand l'option n'est pas activé on obtiens deux résultats:
- pharmacocinétique
- tique

i.2. Quand l'option est activé on obtiens un seul résultat:
- pharmacocinétique

**(ii) Daemon**
Les deux options Match Longest Only et Match Whole Word (l'inverse de l'interface) sont disponibles.

ii.1. Match Longest Only et Match Whole World:
- pharmacocinétique

ii.2. Match Longest Only et !(Match Whole World)
- pharmacocinétique

ii.3. !(Match Longest Only) et Match Whole World
- pharmacocinétique
- tique

ii.4. !(Match Longest Only) et !(Match Whole World)
- pharmacocinétique
- cinétique
- tique

On obtiens les memes résultats du daemon sur le l'annotateur du lirmm bioportal avec les paramètres Match Longest Only et Match Partial Words.

**Comment by jonquet** [comment]
Je vais contacter les gens de UMich maintenant que le bug est plus précis.

**Comment by jonquet** [comment]
Short summary in English for the Umich folks ;)

Every time MGREP sees a word with an accent, it considers the string right after the accent as a new word as well as considering the whole word.
See the example with "pharmacocinétique" and results with the daemon.

**Comment by jonquet** [comment]
@amineabdaoui Can you tell me the word divider that is used ? (I forgot about this parameter).

 mgrep -m batch-mapping -w NonAlphanumeric -d dict.txt < corpus.txt
       -d, --dictionary-file=FILE
              FILE is a two-column tab-delimited file. The first column is a
                signed 64-bit integer, the second column is the text
                associated with the concept
       -w, --word-divider=None|NonAlphanumeric|FILE
              'None' means no word-divider characters, all matches are
                 printed
              'NonAlphanumeric' is a predefined character set, which
                 includes all ASCII characters (1-127), excluding 0-9, a-z,
                 A-Z
              FILE is a file, each line of which is a hexadecimal code,
                followed by ';' and then comments. An example line is
                "2b; ascii code 43, character '+'"
       -c, --casefolding-file=FILE
              ignore case distinctions, FILE can be downloaded at
                http://unicode.org/Public/UNIDATA/CaseFolding.txt
       -l, --longest
              longest match only

We are supposed to have a file parameter: french_word_divider.txt.
Is this really used? It seems we have the by default behaviour.

**Comment by twktheainur** [comment]
@amineabdaoui @jonquet The tests were performed with the default word_divider.txt, the same that is being used on the lirmm portal and stageportal. It would appear that this is the issue. We should create a French word divider file to fix the problem

**Comment by twktheainur** [comment]
We just had a look at the file with @amineabdaoui and removed all accented characters from the divider file. I have deployed the updated file on stageportal. Everything works properly now for all the previous tests. @jonquet You may want to test it yourself on stageportal and if you confirm that it works we can ask @vemonet to push to the production server.

**Comment by jonquet** [comment]
I attach the word divider file that I was using locally.
[french_word_divider.txt](https://github.com/sifrproject/ncbo_annotator/files/724944/french_word_divider.txt)

By the way, there is a new Mgrep version (5.0) that I should pass over soon.

**Comment by jonquet** [comment]
Seems to be still problematic on stage server:
http://services.stageportal.lirmm.fr/annotator?text=pharmacocinétique&longest_only=false&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false&expand_mappings=false

Is the MGREP server restarted with word_divider ?

**Comment by jonquet** [comment]
By the way... the problem seems to be present also with the NCBO Annotator Plus:
http://services.stageportal.lirmm.fr/ncbo_annotatorplus?text=The patient shows no signs of fever. His father already had osteoarthritis. He has a history of depression.&ontologies=MESH&longest_only=false&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false&expand_mappings=false

Whereas it does not happen on the main NCBO Annotator
http://data.bioontology.org/annotator?text=The patient shows no signs of fever. His father already had osteoarthritis. He has a history of depression.&ontologies=MESH&longest_only=false&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false 

Which is kind of weird. Any idea?

**Comment by twktheainur** [comment]
The problem for the French stageportal annotator was that it was using the production annotator URI, which doesn't have to new word divider file. This now works well. 

As for the annotator plus, these examples appear to be working correctly when we call the proxy directly through services.stageportal.lirmm.fr/ncbo_annotator plus, but the problem is present in the interface with the same query. We suspect the web interface uses a cache for the annotator (I imagine redis-http), so when the caches expire the problem should disappear.

**Comment by jonquet** [comment]
For the NCBO Annotator +, this is actually very weird... the call to the web service does not have the problem... and the UI has it... whereas we are not supposed to have any cache here as we are actually proxying to the main NCBO Annotator. 

How come the UI shows results that the API do not return ?
@vemonet any ideas ?

**Comment by twktheainur** [comment]
I had a look at request executed by the interface when the button is pressed, it's a POST request directed at stageportal.lirmm.fr/ncbo_annotatorplus:

http://stageportal.lirmm.fr/ncbo_annotatorplus?exclude_numbers=false&exclude_synonyms=false&expand_mappings=false&longest_only=false&ncbo_slice=&ontologies=&raw=true&score=&text=The%20patient%20shows%20no%20signs%20of%20fever.%20His%20father%20already%20had%20osteoarthritis.%20He%20has%20a%20history%20of%20depression.&whole_word_only=true

What is odd is that this request is received by the tomcat server on services.stageportal but the annotations logged in catalina.out contain this problem. I will add debug messages to the proxy to see if it really goes through the proxy and where exactly the error occurs

**Comment by twktheainur** [comment]
If I use the interface, the proxy forwards: 

http://data.bioontology.org/annotator?include=prefLabel&recognizer=&apikey=key&whole_word_only=false&exclude_synonyms=false&ontologies=MESH&exclude_numbers=false&longest_only=false&text=The+patient+shows+no+signs+of+fever.+His+father+already+had+osteoarthritis.+He+has+a+history+of+depression.

If I use the service directly with the URL provided by the interface, proxy forwards to NCBO Annotator: 

http://data.bioontology.org/annotator?apikey=key&whole_word_only=true&exclude_synonyms=false&ontologies=MESH&expand_mappings=false&exclude_numbers=false&longest_only=false&text=The+patient+shows+no+signs+of+fever.+His+father+already+had+osteoarthritis.+He+has+a+history+of+depression.

**The difference here is that whole_word_only=false when the interface sends the request although "Match partial words" is not selected in the interface. When "Match partial words is selected" the query still contains whole_word_only=false**

So the interface doesn't properly check when "Match partial words" is selected and behaves with a default behaviour where "Match partial words is always activated.

**Comment by vemonet** [comment]
I remember about fixing a little bug about it 
Because in the interface they ask if the user wants to "Match partial words",  but the API param is "whole_word_only" (the opposite... Not really intuitive). I'll fix that tomorrow

**Comment by jonquet** [comment]
Great. I recall also now finding this in the past... mixed like this in the rest of the issues I missed it. Let's fix and close ;)

**Comment by vemonet** [comment]
Fixed on stage and bioportal (it was fixed for the annotator but not the annotator plus)
