### ISSUE TITLE
Probleme avec les caracteres apostrophes

### ISSUE THREAD

**Issue by jonquet** [sifrproject/ncbo_annotator#10]
Pour la phrase: "Il a de l'arthrose. Il a de l’arthrose"

UNe seule annotation remonte avec MSHFRE... 

http://services.bioportal.lirmm.fr/annotator/?text=Il%20a%20de%20l%27arthrose.%20Il%20a%20de%20l%E2%80%99arthrose.&ontologies=MSHFRE&longest_only=false&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false&expand_mappings=false&display_links=false&display_context=false&apikey=c34b7653-0639-4946-81af-8ac76fe809dd

@twktheainur toi qui est un champion pour les encodages... tu vois d'ou cela peut venir ;)

**Comment by amineabdaoui** [comment]
Le caractère **'** (apostrophe) est différent du **’** (right single quotation).
J'ai testé en local, le caractère **’** (right single quotation) passe correctement via l'url.
Visiblement c'est Mgrep qui considère le terme **"l’arthrose"** comme un seul mot.
Je pense qu'il suffit de rajouter le caractère **’** comme séparateur dans le fichier word_divider.txt.

**Comment by jonquet** [comment]
Oui c'est bien ca. J'ai fait le test avec les lignes suivantes dans le french_word_divider.txt file

201D; rigth double quotation
201C; left double quotation
2018; left single quotation
2019; right single quotation 

Et cela marche.
Est-ce que toi ou @vemonet peut ajouter ces lignes sur le divider se stage et bioportal ?

FYI: mon test est dans /data/mgrep/mgrep5.0 sur tubo.lirmm.fr

**Comment by amineabdaoui** [comment]
C'est fait sur stageportal et ça marche effectivement
http://services.stageportal.lirmm.fr/annotator?text="Il a de l'arthrose. Il a de l’arthrose" &longest_only=false&exclude_numbers=false&whole_word_only=true&exclude_synonyms=false&expand_mappings=false 

Je n'ai pas les accès de la machine prod.
@vemonet peux tu le faire ou ajouter mon apikey?

**Comment by jonquet** [comment]
Ok. Fait dans le passage en prod de Mars
