### ISSUE TITLE
Annotator does not match terms with parenthesis

### ISSUE THREAD

**Issue by jonquet** [sifrproject/ncbo_annotator#21]
TRy to annotate
    PFGE (test de réparation)
which is the pref label of 
http://bioportal.lirmm.fr/ontologies/ONTOTOXNUC/?p=classes&conceptid=http%3A%2F%2Fwww.cea.fr%2Fontotoxnuc%23PFGETtestDeReparation
No annotation.

**Comment by jonquet** [comment]
Idem with labels with specific characters such as : 

RAI : IDENTIFICATION
http://bioportal.lirmm.fr/ontologies/NABM?p=classes&conceptid=http%3A%2F%2Fchu-rouen.fr%2Fcismef%2FNABM%231131

This must come from Mgrep delimiters.

**Comment by jonquet** [comment]
groupe de patients ou de personnes handicapées
http://bioportal.lirmm.fr/ontologies/STY?p=classes&conceptid=http%3A%2F%2Fpurl.lirmm.fr%2Fontology%2FSTY%2FT101

**Comment by twktheainur** [comment]
The problem it solved, restored appropriate delimiters (to be sure, didn't seem to be an issue there), regenerated the cache and the dictionary and the problem has now disappeared, not sure as to the cause, but I think it was a transient problem due to inconsistencies in the cache
