### ISSUE TITLE
Modify the current annotator workflow to handle the new lemmatization parameter 

### ISSUE THREAD

**Issue by jonquet** [sifrproject/ncbo_annotator#5]
This is a subtask of #4
This task consists in changing the current SIFR Annotator code to enable to use, when &normalize_text=true, another dictionary created explicitly (and itself normalized)

**Comment by amineabdaoui** [comment]
I added a parameter called "**lemmatize**".
If **lemmatize=true**, we call the second Mgrep (which uses the lemmatized dictionary).
Otherwise, we call the default Mgrep (which uses the original dictionary) .

**Comment by jonquet** [comment]
Moved to production end of March.
